### ISSUE TITLE
Snakemake Workflow

### ISSUE THREAD

**Issue by chrissev** [bhattlab/bhattlab_workflows#3]
**This was my command:**
snakemake --configfile ~/asbhatt/chris/project/gutdecon/testpoop/testpoop1.yaml.txt -s ~/asbhatt/chris/tools/bhattlab_workflows/preprocessing/preprocessing.snakefile

**Here is my .yaml file**
specify directories
raw_reads_directory: ~/asbhatt/chris/project/gutdecon/18-11-1_chris_gutdecon1/2.test_subset
output_directory: ~/asbhatt/chris/project/gutdecon/testpoop/testpoopoutput

specify parameters for TrimGalore -- automatically chcecks the adaptor type
trim_galore:
quality: 30
start_trim: 15
end_trim: 0
min_read_length: 60

rm_host_reads:
host_pre: bowtie_index_prefix (i.e. hg19 or mm10)
host_genome: /path/to/genome/fastq/prefix

**Here's my Output**

SyntaxError in line 78 of /home/cseveryn/asbhatt/chris/tools/bhattlab_workflows/preprocessing/preprocessing.snakefile:
invalid syntax

Thank you!  =^)

**Comment by jribado** [comment]
Fixed -- make sure the file suffixes are changes to _R1/R2.fastq.gz as per the README before attempting to run again.

**Comment by elimoss** [comment]
The reason there aren’t is because hash is interpreted in the git markup
syntax as a header, which made the formatting very strange.



On November 5, 2018 at 6:27:41 PM, jribado (notifications@github.com) wrote:

Also! The lines that start with 'specify' should have a # at the start to
indicate they are a comment in case there are issues there like in the
example.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/bhattlab/bhattlab_workflows/issues/3#issuecomment-436109638>,
or mute the thread
